language: ruby
rvm:
  - 2.3.1

cache:
  bundler: true

services:
  - postgresql
  - redis-server

addons:
  postgresql: '9.4'
  code_climate:
    repo_token: f100b0361948e77048cb6cd93dd3431a9f08e37f21815ee3738cd9380d6a54f2

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake

after_success:
  - bundle exec codeclimate-test-reporter
