language: ruby
rvm:
  - 2.3.1

env:
  global:
    - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d

cache:
  bundler: true

services:
  - postgresql
  - redis-server

addons:
  postgresql: '9.4'
  code_climate:
    repo_token: f100b0361948e77048cb6cd93dd3431a9f08e37f21815ee3738cd9380d6a54f2

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake
  - bundle exec rspec

after_success:
  - bundle exec codeclimate-test-reporter

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
