language: ruby
rvm:
  - 2.3.1

cache:
  bundler: true

services:
  - postgresql
  - redis-server

addons:
  postgresql: '9.4'
  # code_climate:
  #   repo_token: d7ec66695ffe27eab60a4009ad71ee97c99fed36e66470e7534076b9af4410e9

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake

after_success:
  # - bundle exec codeclimate-test-reporter
