development: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000
  database: 'pingegram_development'

test:
  <<: *default
  database: pingegram_test
